(base) doc_ayush@astro-A320M-S2H:~/GRB Analysis/Likelihood Analysis/1633+382/Py analysis/new_analysis$ conda activate fermi
(fermi) doc_ayush@astro-A320M-S2H:~/GRB Analysis/Likelihood Analysis/1633+382/Py analysis/new_analysis$ punlearn gtexpmap
(fermi) doc_ayush@astro-A320M-S2H:~/GRB Analysis/Likelihood Analysis/1633+382/Py analysis/new_analysis$ ls -1 *PH*.fits > 1633+382_events.list
(fermi) doc_ayush@astro-A320M-S2H:~/GRB Analysis/Likelihood Analysis/1633+382/Py analysis/new_analysis$ python
Python 3.7.13 (default, Mar 29 2022, 02:18:16) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
>>> import gt_apps as my_apps
>>> 
>>> 
>>> my_apps.filter['evclass'] = 128
>>> my_apps.filter['ra'] = 248.815
>>> my_apps.filter['dec'] = 38.1346
>>> my_apps.filter['rad'] = 15
>>> my_apps.filter['emin'] = 100
>>> my_apps.filter['emax'] = 300000
>>> my_apps.filter['zmax'] = 100
>>> my_apps.filter['tmin'] = 660799526
>>> my_apps.filter['tmax'] = 676351526
>>> my_apps.filter['infile'] = '@1633+382_events.list'
>>> my_apps.filter['outfile'] = '1633+382_filtered.fits'
>>> my_apps.filter.run()
time -p gtselect infile=@1633+382_events.list outfile=1633+382_filtered.fits ra=248.815 dec=38.1346 rad=15.0 tmin=660799526.0 tmax=676351526.0 emin=100.0 emax=300000.0 zmin=0.0 zmax=100.0 evclass=128 evtype="INDEF" convtype=-1 phasemin=0.0 phasemax=1.0 evtable="EVENTS" chatter=2 clobber=yes debug=no gui=no mode="ql"
Done.
real 1.68
user 0.95
sys 0.09
>>> my_apps.filter.command()
'time -p gtselect infile=@1633+382_events.list outfile=1633+382_filtered.fits ra=248.815 dec=38.1346 rad=15.0 tmin=660799526.0 tmax=676351526.0 emin=100.0 emax=300000.0 zmin=0.0 zmax=100.0 evclass=128 evtype="INDEF" convtype=-1 phasemin=0.0 phasemax=1.0 evtable="EVENTS" chatter=2 clobber=yes debug=no gui=no mode="ql"'
>>> 
>>> 
>>> my_apps.filter['scfile'] = 'spacecraft.fits'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/doc_ayush/anaconda3/envs/fermi/lib/python3.7/site-packages/fermitools/GtApp.py", line 43, in __setitem__
    self.pars[key] = value
  File "/home/doc_ayush/anaconda3/envs/fermi/lib/python3.7/site-packages/fermitools/pil.py", line 74, in __setitem__
    raise KeyError(name)
KeyError: 'scfile'
>>> 
>>> 
>>> my_apps.maketime['scfile'] = 'spacecraft.fits'
>>> my_apps.maketime['filter'] = '(DATA_QUAL>0)&&(LAT_CONFIG==1)'
>>> my_apps.maketime['roicut'] = 'yes'
>>> my_apps.maketime['evfile'] = '1633+382_filtered.fits'
>>> my_apps.maketime['outfile'] = '1633+382_filtered_gti.fits'
>>> my_apps.maketime.run()
time -p gtmktime scfile=spacecraft.fits sctable="SC_DATA" filter="(DATA_QUAL>0)&&(LAT_CONFIG==1)" roicut=yes evfile=1633+382_filtered.fits evtable="EVENTS" outfile="1633+382_filtered_gti.fits" apply_filter=yes overwrite=no header_obstimes=yes tstart=0.0 tstop=0.0 gtifile="default" chatter=2 clobber=yes debug=no gui=no mode="ql"
real 0.75
user 0.63
sys 0.07
>>> 
>>> 
>>> my_apps.expCube['evfile'] = '1633+382_filtered_gti.fits'
>>> my_apps.expCube['scfile'] = 'spacecraft.fits'
>>> my_apps.expCube['outfile'] = '1633+382_ltCube.fits'
>>> my_apps.expCube['dcostheta'] = 0.025
>>> my_apps.expCube['binsz'] = 1
>>> my_apps.expCube.run()
time -p gtltcube evfile="1633+382_filtered_gti.fits" evtable="EVENTS" scfile=spacecraft.fits sctable="SC_DATA" outfile=1633+382_ltCube.fits dcostheta=0.025 binsz=1.0 phibins=0 tmin=0.0 tmax=0.0 file_version="1" zmin=0.0 zmax=180.0 chatter=2 clobber=yes debug=no gui=no mode="ql"
Working on file spacecraft.fits
.....................!
real 843.49
user 839.81
sys 0.88
>>> 
>>> 
>>> from GtApp import GtApp
>>> expCubeSun = GtApp('gtltcubesun','Likelihood')
>>> expCubeSun.command()
'time -p gtltcubesun evfile="" evtable="EVENTS" scfile= sctable="SC_DATA" outfile=expCube.fits body="SUN" dcostheta=0.025 thetasunmax=180.0 binsz=0.5 phibins=0 tmin=0.0 tmax=0.0 powerbinsun=2.7 file_version="1" zmax=180.0 chatter=2 clobber=yes debug=no gui=no mode="ql"'
>>> 
>>> 
>>> my_apps.expMap['evfile'] = '1633+382_filtered_gti.fits'
>>> my_apps.expMap['scfile'] = 'spacecraft.fits'
>>> my_apps.expMap['expcube'] = '1633+382_ltCube.fits'
>>> my_apps.expMap['outfile'] = '1633+382_expMap.fits'
>>> my_apps.expMap['irfs'] = 'CALDB'
>>> my_apps.expMap['srcrad'] = 15
>>> my_apps.expMap['nlong'] = 120
>>> my_apps.expMap['nlat'] = 120
>>> my_apps.expMap['nenergies'] = 30
>>> my_apps.expMap.run()
time -p gtexpmap evfile=1633+382_filtered_gti.fits evtable="EVENTS" scfile=spacecraft.fits sctable="SC_DATA" expcube=1633+382_ltCube.fits outfile=1633+382_expMap.fits irfs="CALDB" evtype="INDEF" srcrad=15.0 nlong=120 nlat=120 nenergies=30 submap=no nlongmin=0 nlongmax=0 nlatmin=0 nlatmax=0 chatter=2 clobber=yes debug=no gui=no mode="ql"
The exposure maps generated by this tool are meant
to be used for *unbinned* likelihood analysis only.
Do not use them for binned analyses.
Caught St13runtime_error at the top level: RoiCuts::sortCuts:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/doc_ayush/anaconda3/envs/fermi/lib/python3.7/site-packages/fermitools/GtApp.py", line 76, in run
    raise RuntimeError (self.appName + " execution failed")
RuntimeError: gtexpmap execution failed
>>> 
>>> 

